version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 1
    ignore:
      - dependency-name: regex

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 1

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase
    cooldown:
      default-days: 1
      exclude:
        - '@standard-config/*'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
