packages:
  - packages/*

autoInstallPeers: false

catalog:
  '@standard-config/tsconfig': ^3.2.0
  '@vitest/coverage-v8': ^4.1.8
  prettier: ^3.8.3
  typescript: ^6.0.3
  vitest: ^4.1.8

color: always

overrides:
  vite-plus>oxfmt: '-'

peerDependencyRules:
  allowAny:
    - '@vitest/coverage-v8'
    - vitest

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - ast-v8-to-istanbul@1.0.2
  - tinyexec@1.2.2

updateConfig:
  ignoreDependencies:
    - '@types/node'
