packages:
  - packages/*

autoInstallPeers: false

catalog:
  '@standard-config/tsconfig': ^3.2.0
  '@vitest/coverage-v8': ^4.1.9
  oxlint: ^1.69.0
  prettier: ^3.8.4
  typescript: ^6.0.3
  vitest: ^4.1.9

color: always

overrides:
  vite-plus>oxfmt: '-'
  vite-plus>oxlint: 'catalog:'

peerDependencyRules:
  allowAny:
    - '@vitest/coverage-v8'
    - vitest

strictPeerDependencies: true

trustPolicy: no-downgrade

updateConfig:
  ignoreDependencies:
    - '@types/node'
