packages:
  - packages/*

autoInstallPeers: false

catalog:
  prettier: ^3.8.1

onlyBuiltDependencies:
  - esbuild

peerDependencyRules:
  allowedVersions:
    eslint: '*'
    vitest: '*'

strictPeerDependencies: true

updateConfig:
  ignoreDependencies:
    - '@types/node'
