#!/bin/sh

# Enable strict mode
set -eu

# Ensure all dependencies are up to date
pnpm --silent install --ignore-scripts --frozen-lockfile

# Lint staged files
pnpm vp staged --concurrent=false --relative
