name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  sync:
    if: ${{ github.event_name == 'push' }}
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
      - run: sw_vers
      - run: bin/domfiles-sync
      - run: fish --command 'domfiles sync'

  test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
        with:
          cache: true
      - run: brew install fish
      - run: pnpm install
      - run: pnpm test
