name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  sync:
    if: ${{ github.event_name == 'push' }}
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - run: sw_vers
      - run: home/.local/bin/domfiles-sync
      - run: fish --command 'domfiles sync'

  test-rs:
    name: test / rs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1.17.0
      - run: cargo test --locked --workspace

  test-ts:
    name: lint / ts
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - run: brew install fish rust taplo
      - uses: pnpm/setup@v2.1.0
        with:
          cache: true
          runtime: node@24
      - run: pnpm test:ts
