name: Verify

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  format:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - run: brew install fish
      - uses: pnpm/setup@v2.0.0
        with:
          cache: true
          runtime: node@24
      - run: pnpm format:check

  lint-fish:
    name: lint / fish
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - run: brew install fish
      - run: bin/domfiles-dev-lint-fish

  lint-sh:
    name: lint / sh
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - run: brew install shellcheck
      - run: bin/domfiles-dev-lint-sh

  lint-ts:
    name: lint / ts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/setup@v2.0.0
        with:
          cache: true
          runtime: node@24
      - run: pnpm lint:ts:check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: pnpm/setup@v2.0.0
        with:
          cache: true
          runtime: node@24
      - run: pnpm --recursive --include-workspace-root typecheck
